// This file is generated by `npm run releases:sync`. Do not edit by hand.
// Source: /Users/colinfreed/Projects/AdventureWare/Products/Kwipoo/app/releases/derived/website/releases.json
import type { WebsiteReleaseNote } from "./releases";

export const generatedReleaseNotes: WebsiteReleaseNote[] = [
  {
    version: "1.7.1",
    slug: "cleaner-cost-entry-and-more-reliable-image-uploads",
    publishedAt: "2026-04-01",
    title: "Cleaner cost entry and more reliable image uploads",
    summary:
      "Kwipoo now keeps decimal cost entry steady while you type and makes place and thing image uploads update production records immediately after success.",
    highlights: [
      "The Thing cost field now keeps decimal amounts in place while typing and normalizes pasted currency values more cleanly.",
      "Place and Thing image uploads now update production records immediately after a successful upload instead of waiting on offline mutation sync.",
    ],
    details: [
      "Cost entry is less frustrating when typing cents or pasting formatted values from other apps.",
      "Successful image uploads now show up more reliably in live production data without depending on a later offline sync pass.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
  {
    version: "1.7.0",
    slug: "import-things-and-steadier-everyday-interactions",
    publishedAt: "2026-03-31",
    title: "Import Things and steadier everyday interactions",
    summary:
      "This release introduced Import Things for bulk entry, polished shared cards and detail drawers, and made actions, menus, and loading states more consistent throughout the app.",
    highlights: [
      "A new Import Things flow lets you paste or map a list of items, review them, and save them with shared defaults.",
      "Shared place and set cards, detail drawers, and action rows are more consistent across interactive states, menus, and selection flows.",
      "Auth, search, friend flows, and other loading or error states now give clearer feedback and avoid duplicate actions more reliably.",
    ],
    details: [
      "The Import Things experience now includes clearer CSV guidance, stronger review summaries, and a full-screen modal with more room to work.",
      "Thing, set, event, and move-to-spot drawers now share steadier controls for toggles, back actions, menus, and focus handling.",
      "Public profile, event attendee, invitee, and friend discovery flows now behave more consistently across mobile and desktop.",
    ],
    importance: "notable",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
    ctaLabel: "Open What's New",
    ctaHref: "/updates",
  },
  {
    version: "1.6.0",
    slug: "faster-ways-to-add-reuse-and-duplicate-things",
    publishedAt: "2026-03-26",
    title: "Faster ways to add, reuse, and duplicate Things",
    summary:
      "Kwipoo added quicker ways to create Things, including Add Similar, Add Multiple, Add from Photo, and Duplicate Thing, while tightening dialog behavior and add-item reliability across the app.",
    highlights: [
      "New Add Similar, Add Multiple, Add from Photo, and Duplicate Thing flows make it much faster to create related items without starting from scratch.",
      "Add-Thing flows are more reliable across Set, Event, and move-to-spot contexts, so new items land in the right place more consistently.",
      "Dialogs, settings drawers, search labels, and public profile or chat layouts got accessibility and navigation improvements.",
    ],
    details: [
      "The default Save & Add Another flow now stays blank between items, while Add Multiple intentionally carries forward repeated fields for batch entry.",
      "Drawer history, scroll restoration, and back navigation are steadier, especially across settings and detail flows.",
      "Several save, invite, and chat actions now surface sync or permission failures more reliably instead of failing quietly.",
    ],
    importance: "notable",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
    ctaLabel: "Open What's New",
    ctaHref: "/updates",
  },
  {
    version: "1.5.4",
    slug: "welcome-quick-start-and-faster-add-flows",
    publishedAt: "2026-03-25",
    title: "A clearer start and faster everyday entry",
    summary:
      "Kwipoo now gets new users to a useful first setup faster, makes repeat item entry lighter, and handles app feedback more reliably across drawers, notifications, and event flows.",
    highlights: [
      "New users now land on a real welcome quick-start page with clearer guidance for Places, Spots, and Things.",
      "Adding Things is faster with a lighter quick-add path, add-and-continue entry, and reusable recent values.",
      "Notifications, event flows, and shared feedback states are more reliable when loading, retrying, or recovering from errors.",
    ],
    details: [
      "The Thing form now stays focused on the fastest common path while keeping optional details out of the way until needed.",
      "Spot and category assignment flows now keep more context when creating a new Thing from inside another task.",
      "Several drawer, list, and event-detail states now handle loading and failure cases more cleanly instead of flashing or dropping users into awkward states.",
    ],
    importance: "notable",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
    ctaLabel: "Open What's New",
    ctaHref: "/updates",
  },
  {
    version: "1.5.3",
    slug: "cleaner-sync-status-and-startup-routing",
    publishedAt: "2026-03-23",
    title: "Cleaner sync status and sturdier startup handling",
    summary:
      "This release tightened startup routing, improved upload consistency, and made sync status easier to understand without shifting the page around.",
    highlights: [
      "Signed-in startup routing and offline shell warmup now keep private routes cached and redirect more reliably.",
      "Image uploads across Things, Places, and profile photos are prepared more consistently before storage.",
      "The sync status banner is clearer about offline, syncing, success, and failure states.",
    ],
    details: [
      "Deleting a Place now updates the page immediately so removed items disappear without a reload.",
      "Sync status messaging replaces the older offline banner with clearer state changes and steadier placement.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
  {
    version: "1.5.2",
    slug: "steadier-sync-panels-and-auth-fixes",
    publishedAt: "2026-03-20",
    title: "Steadier sync panels and auth fixes",
    summary:
      "Kwipoo now keeps sync status more stable across navigation, improves login reliability, and continues tightening detail and upload behavior.",
    highlights: [
      "Collection sync status now stays stable across page navigation and shows the right attention state more consistently.",
      "Google and Apple sign-in flows were fixed across browser and iOS wrapper login paths.",
      "Connectivity, uploads, and detail-drawer actions got smaller reliability and polish improvements.",
    ],
    details: [
      "Thing sharing controls moved into a more consistent position in the detail drawer.",
      "Adding a Thing with a photo now waits for its initial sync before attaching the image.",
      "Navigation tiles no longer trigger unwanted long-press and context-menu behavior.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
  {
    version: "1.5.1",
    slug: "ui-foundations-and-upload-reliability",
    publishedAt: "2026-03-19",
    title: "UI foundations and upload reliability",
    summary:
      "This release improved shared UI consistency, tightened auth flows, and made uploads and offline sync more dependable.",
    highlights: [
      "Shared UI foundations are more consistent, with stronger house-style primitives for auth and future screens.",
      "Login, signup, and auth callback flows now handle redirects and failures more cleanly.",
      "Thing image uploads and offline set syncing are more reliable after reconnects and first saves.",
    ],
    details: [
      "Validation feedback for shared text fields now waits until blur instead of reacting on every keystroke.",
      "Auth screens were tightened on phones and tablets to reduce oversized spacing.",
      "Place detail media was restored so places show their photo area correctly again.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
];
