// This file is generated by `npm run releases:sync`. Do not edit by hand.
// Source: /Users/colinfreed/Projects/AdventureWare/Products/Kwipoo/app/releases/derived/website/releases.json
import type { WebsiteReleaseNote } from "./releases";

export const generatedReleaseNotes: WebsiteReleaseNote[] = [
  {
    version: "1.7.1",
    slug: "cleaner-cost-entry-and-more-reliable-image-uploads",
    publishedAt: "2026-04-01",
    title: "Easier cost entry and faster photo updates",
    summary:
      "Typing prices is less frustrating, and new photos for Things and Places show up sooner after you upload them.",
    highlights: [
      "The Thing cost field keeps decimal amounts in place while you type and cleans up pasted currency values more naturally.",
      "Place and Thing photos update right after a successful upload instead of waiting for a later sync.",
    ],
    details: [
      "Entering cents or pasting a formatted price from another app is less likely to fight your cursor.",
      "Successful photo uploads appear in live data sooner, so you can confirm the change right away.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
  {
    version: "1.7.0",
    slug: "import-things-and-steadier-everyday-interactions",
    publishedAt: "2026-03-31",
    title: "Import Things from a list",
    summary:
      "You can now bring in a batch of Things from a list, and a round of drawer, menu, and loading-state cleanup makes everyday actions easier to trust.",
    highlights: [
      "Import Things lets you paste or map a list of items, review them, and save them with shared defaults.",
      "The import flow includes clearer CSV guidance, stronger review summaries, and a full-screen workspace with more room to check your list.",
      "Auth, search, friend flows, cards, and detail drawers now give clearer feedback and do a better job preventing duplicate actions.",
    ],
    details: [
      "Place and Set cards, detail drawers, and action rows were cleaned up so common actions are easier to scan and use.",
      "Thing, Set, Event, and move-to-spot drawers now behave better around toggles, back actions, menus, and focus.",
      "Public profiles, attendee lists, invitee views, and friend discovery feel more consistent across mobile and desktop.",
    ],
    importance: "notable",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
    ctaLabel: "Open What's New",
    ctaHref: "/updates",
  },
  {
    version: "1.6.0",
    slug: "faster-ways-to-add-reuse-and-duplicate-things",
    publishedAt: "2026-03-26",
    title: "More ways to add Things faster",
    summary:
      "You can now duplicate a Thing, add several at once, start from a similar item, or build a list from a photo, with smoother add-item flows around the app.",
    highlights: [
      "New Add Similar, Add Multiple, Add from Photo, and Duplicate Thing options help you create related items without starting from scratch.",
      "Add-Thing flows work more reliably from Sets, Events, and move-to-spot flows, so new items land in the right place more often.",
      "Dialogs, settings drawers, search labels, and public profile or chat layouts are easier to navigate and use.",
    ],
    details: [
      "Save and Add Another now clears the form between items, while Add Multiple intentionally carries forward repeated fields for batch entry.",
      "Back navigation and scroll position hold up better across settings and detail flows.",
      "Save, invite, and chat actions now surface sync or permission problems instead of failing quietly.",
    ],
    importance: "notable",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
    ctaLabel: "Open What's New",
    ctaHref: "/updates",
  },
  {
    version: "1.5.4",
    slug: "welcome-quick-start-and-faster-add-flows",
    publishedAt: "2026-03-25",
    title: "A clearer welcome and faster Thing entry",
    summary:
      "New users get a clearer first setup, repeat Thing entry takes fewer taps, and the app does a better job showing loading, retry, and recovery states.",
    highlights: [
      "New users now land on a quick-start welcome that explains Places, Spots, and Things before they dive in.",
      "Adding Things is faster with quick add, Save and Add Another, and reusable recent values.",
      "Notifications and event flows do a better job showing loading, retry, and recovery states when something goes wrong.",
    ],
    details: [
      "The Thing form stays focused on the most common path, with optional details tucked out of the way until you need them.",
      "Creating a new Thing from another task keeps more spot and category context.",
      "Several drawers, lists, and event details now handle loading and failure states without awkward flashes or dead ends.",
    ],
    importance: "notable",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
    ctaLabel: "Open What's New",
    ctaHref: "/updates",
  },
  {
    version: "1.5.3",
    slug: "cleaner-sync-status-and-startup-routing",
    publishedAt: "2026-03-23",
    title: "Clearer sync status and smoother startup",
    summary:
      "Opening the app is more predictable, upload prep is more dependable, and sync status is easier to read without jumping around the page.",
    highlights: [
      "Signed-in startup now sends you to the right screen more reliably, including after offline warmup.",
      "Uploads for Things, Places, and profile photos are prepared more reliably before they are sent.",
      "The sync status banner now makes offline, syncing, success, and failure states easier to understand.",
    ],
    details: [
      "Deleting a Place removes it from the page right away instead of waiting for a reload.",
      "The old offline banner has been replaced with clearer sync messages that stay in one place.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
  {
    version: "1.5.2",
    slug: "clearer-sync-status-and-better-sign-in",
    publishedAt: "2026-03-20",
    title: "Clearer sync status and better sign-in",
    summary:
      "Sign-in works more reliably, sync status stays visible as you move around the app, and a few everyday interactions are less finicky.",
    highlights: [
      "Collection sync status now stays put as you navigate, so it is easier to tell when something needs attention.",
      "Google and Apple sign-in were fixed across the browser app and the iOS wrapper.",
      "Adding a Thing with a photo now waits for the first save before attaching the image, which helps avoid failed uploads.",
    ],
    details: [
      "Thing sharing controls are easier to find in the detail drawer.",
      "Navigation tiles no longer trigger accidental long-press or context-menu behavior.",
      "Smaller connectivity and upload fixes reduce interruptions while you work.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
  {
    version: "1.5.1",
    slug: "ui-foundations-and-upload-reliability",
    publishedAt: "2026-03-19",
    title: "Smoother sign-in and more dependable uploads",
    summary:
      "Signing in is smoother, uploads are less likely to get stuck, and saved changes hold up better after you reconnect.",
    highlights: [
      "Login, sign-up, and auth callback screens now handle redirects and failures with clearer recovery.",
      "Thing photo uploads and offline set syncing are more dependable after a reconnect or first save.",
      "Shared form fields behave better, so common actions feel less fussy while you move through the app.",
    ],
    details: [
      "Validation messages for shared text fields now wait until you finish typing instead of reacting to every keystroke.",
      "Auth screens fit phones and tablets better, with less oversized spacing.",
      "Place details show their photo area correctly again.",
    ],
    importance: "quiet",
    platformTargets: ["web", "ios_wrapper", "android_wrapper"],
  },
];
