// This file is generated by `npm run docs:sync`. Do not edit by hand.
// Source: /Users/colinfreed/Projects/AdventureWare/Products/Kwipoo/app/docs/derived/website/docs-reference.json
import type { DocsEntityReference } from "./entity-reference";

export const generatedDocsEntityReferences: DocsEntityReference[] = [
  {
    slug: "things",
    label: "Things",
    summary:
      "Physical items you own and want to track, search, move, and reuse in sets or events.",
    routePath: "/things",
    schemaExport: "thingSchema",
    schemaFile: "src/lib/schemas.ts",
    formFile: "src/lib/forms/ThingForm.svelte",
    routeFiles: [
      "src/routes/(app)/things/+page.svelte",
      "src/routes/(app)/things/ThingDetail.svelte",
    ],
    fields: [
      {
        key: "name",
        label: "Name",
        status: "Required",
        description:
          "Primary item name shown in lists, detail views, and search.",
        example: "Mountain Bike",
      },
      {
        key: "category",
        label: "Category",
        status: "Optional",
        description:
          "Flexible category used for grouping, filters, summaries, and reuse across the product.",
        example: "Camping",
      },
      {
        key: "brand",
        label: "Brand",
        status: "Optional",
        description: "Brand or manufacturer name for the item.",
        example: "Trek",
      },
      {
        key: "description",
        label: "Description",
        status: "Optional",
        description:
          "Freeform notes that help identify the item or remember useful context later.",
        example: "Bought in 2020, aluminum frame, 21-speed",
      },
      {
        key: "visibility",
        label: "Visibility",
        status: "Defaulted",
        description:
          "Controls who can see the item: Public, Friends Only, or Owner Only.",
        example: "Friends Only",
      },
      {
        key: "weight",
        label: "Weight",
        status: "Optional",
        description:
          "Used for packing, totals, and planning when weight matters.",
        example: "15.2",
      },
      {
        key: "weight_unit_id",
        label: "Weight Unit",
        status: "Defaulted",
        description:
          "Unit paired with the weight field, using the profile default unless changed.",
        example: "lb",
      },
      {
        key: "purchase_source",
        label: "Source",
        status: "Optional",
        description: "Where or from whom you got the item.",
        example: "REI",
      },
      {
        key: "quantity",
        label: "Quantity",
        status: "Defaulted",
        description:
          "How many identical units this entry represents. Starts at 1.",
        example: "2",
      },
      {
        key: "purchase_price",
        label: "Cost",
        status: "Optional",
        description: "Purchase price or recorded value for the item.",
        example: "$500",
      },
      {
        key: "purchase_date",
        label: "Acquisition Date",
        status: "Optional",
        description: "When you bought or acquired the item.",
        example: "2021-08-15",
      },
      {
        key: "condition",
        label: "Condition",
        status: "Defaulted",
        description:
          "Condition score used to describe overall state. Starts at the default midrange value.",
        example: "5 - Very Good",
      },
      {
        key: "model",
        label: "Model",
        status: "Optional",
        description: "Model name or model number for the item.",
        example: "Marlin 7",
      },
      {
        key: "product_identifier",
        label: "Product ID",
        status: "Optional",
        description:
          "Product number, UPC, or another identifier separate from serial number.",
        example: "UPC-654789",
      },
      {
        key: "serial_number",
        label: "Serial Number",
        status: "Optional",
        description: "Unique identifier for this specific item.",
        example: "SN12345ABC",
      },
    ],
  },
  {
    slug: "places",
    label: "Places",
    summary:
      "Top-level real-world locations that organize where things live before you get more specific with spots.",
    routePath: "/places",
    schemaExport: "placeSchema",
    schemaFile: "src/lib/schemas.ts",
    formFile: "src/lib/forms/PlaceForm.svelte",
    routeFiles: [
      "src/routes/(app)/places/+page.svelte",
      "src/routes/(app)/places/PlaceDetail.svelte",
    ],
    fields: [
      {
        key: "name",
        label: "Place Name",
        status: "Required",
        description: "Friendly name for the location.",
        example: "Home",
      },
      {
        key: "description",
        label: "Description",
        status: "Optional",
        description: "Extra context about the location.",
        example: "Main house with basement",
      },
      {
        key: "type",
        label: "Type",
        status: "Defaulted",
        description:
          "Preset place type shown in the form with a default selection.",
        example: "House",
      },
      {
        key: "visibility",
        label: "Visibility",
        status: "Defaulted",
        description:
          "Controls who can see the place: Public, Friends Only, or Owner Only.",
        example: "Friends Only",
      },
      {
        key: "address_line1",
        label: "Address Line 1",
        status: "Optional",
        description: "Primary address line for the place.",
        example: "123 Main St",
      },
      {
        key: "address_line2",
        label: "Address Line 2",
        status: "Optional",
        description: "Secondary address line, suite, or unit info.",
        example: "Apt 5B",
      },
      {
        key: "city",
        label: "City",
        status: "Optional",
        description: "City where the place is located.",
        example: "Denver",
      },
      {
        key: "state",
        label: "State",
        status: "Optional",
        description: "State, province, or region.",
        example: "CO",
      },
      {
        key: "postal_code",
        label: "Postal Code",
        status: "Optional",
        description: "ZIP or postal code.",
        example: "80203",
      },
      {
        key: "country",
        label: "Country",
        status: "Optional",
        description: "Country where the place is located.",
        example: "United States",
      },
    ],
  },
  {
    slug: "spots",
    label: "Spots",
    summary:
      "Precise storage areas inside a place or inside a container thing.",
    routePath: "/places",
    schemaExport: "spotSchema",
    schemaFile: "src/lib/schemas.ts",
    formFile: "src/lib/forms/SpotForm.svelte",
    routeFiles: [
      "src/routes/(app)/places/SpotDetail.svelte",
      "src/routes/(app)/things/SpotList.svelte",
    ],
    fields: [
      {
        key: "name",
        label: "Name",
        status: "Required",
        description: "The precise storage location name.",
        example: "Hall closet shelf",
      },
      {
        key: "description",
        label: "Description",
        status: "Optional",
        description: "Extra context about this spot.",
        example: "Closet near the front door",
      },
      {
        key: "visibility",
        label: "Visibility",
        status: "Defaulted",
        description:
          "Controls who can see the spot: Public, Friends Only, or Owner Only.",
        example: "Friends Only",
      },
    ],
  },
  {
    slug: "sets",
    label: "Sets",
    summary:
      "Reusable groups of things for packing, routines, hobbies, and recurring setups.",
    routePath: "/things",
    schemaExport: "setSchema",
    schemaFile: "src/lib/schemas.ts",
    formFile: "src/lib/forms/SetForm.svelte",
    routeFiles: [
      "src/routes/(app)/things/SetList.svelte",
      "src/routes/(app)/things/SetDetail.svelte",
    ],
    fields: [
      {
        key: "name",
        label: "Name",
        status: "Required",
        description: "Name for the reusable set.",
        example: "Winter Camping Kit",
      },
      {
        key: "description",
        label: "Description",
        status: "Optional",
        description: "Context, intent, or notes for the set.",
        example: "Gear for 3-4 day trips",
      },
      {
        key: "category",
        label: "Type",
        status: "Optional",
        description: "Freeform set type or purpose.",
        example: "Travel",
      },
      {
        key: "visibility",
        label: "Visibility",
        status: "Defaulted",
        description:
          "Controls who can see the set: Public, Friends Only, or Owner Only.",
        example: "Friends Only",
      },
    ],
  },
  {
    slug: "events",
    label: "Events",
    summary:
      "Plans or trips where you coordinate sets, people, and what still needs to be packed.",
    routePath: "/events",
    schemaExport: "eventSchema",
    schemaFile: "src/lib/schemas.ts",
    formFile: "src/lib/forms/EventForm.svelte",
    routeFiles: [
      "src/routes/(app)/events/+page.svelte",
      "src/routes/(app)/events/EventDetail.svelte",
    ],
    fields: [
      {
        key: "is_solo",
        label: "Solo Event",
        status: "Defaulted",
        description:
          "Toggle that marks whether the event is just for you or can involve others.",
        example: "Off",
      },
      {
        key: "name",
        label: "Name",
        status: "Required",
        description: "Name shown for the event throughout the app.",
        example: "Spring Camping Trip",
      },
      {
        key: "description",
        label: "Description",
        status: "Optional",
        description: "Extra context about the event.",
        example: "Three nights in Moab with cold-weather gear",
      },
      {
        key: "location",
        label: "Location",
        status: "Optional",
        description: "Freeform location details for the event.",
        example: "Moab, Utah",
      },
      {
        key: "start_date",
        label: "Start Date",
        status: "Defaulted",
        description:
          "Start date for the event. Defaults to today when creating.",
        example: "2026-04-10",
      },
      {
        key: "end_date",
        label: "End Date",
        status: "Defaulted",
        description:
          "End date for the event. Defaults to today and must not be earlier than the start date.",
        example: "2026-04-13",
      },
      {
        key: "visibility",
        label: "Visibility",
        status: "Defaulted",
        description:
          "Controls who can see the event: Public, Friends Only, or Owner Only.",
        example: "Friends Only",
      },
    ],
  },
];
